version: "3.7"

services:

  nginx:
    image: nginx:1.19.5
    ports:
      - 80:80
    networks:
      - gii_project1_network
    volumes:
      - /home/ubuntu/nginx.conf:/etc/nginx/nginx.conf
      - gii_project1_static:/data/static/
      - gii_project1_media:/data/media/

  django:
    image: gii_project1:4
    networks:
      - gii_project1_network
    volumes:
      - gii_project1_static:/home/GII_Project/staticfiles/
      - gii_project1_media:/home/GII_Project/media/

  mariadb:
    image: mariadb:10.5
    networks:
      - gii_project1_network
    volumes:
      - mariadb_volume:/var/lib/mysql
    environment:
      MARIADB_ROOT_PASSWORD: password1234
      MARIADB_DATABASE: django
      MARIADB_USER: django
      MARIADB_PASSWORD: password1234


networks:
  gii_project1_network:

volumes:
  gii_project1_static:
  gii_project1_media:
  mariadb_volume: