version: "3.7"

services:

  nginx:
    image: nginx:1.19.5
    ports:
      - 80:80
    networks:
      - gii_project1_network
    volumes:
      - /home/ubuntu/nginx.conf:/etc/nginx/nginx.conf
      - gii_project1_static:/data/static/
      - gii_project1_media:/data/media/

  django:
    image: gii_project1:3
    networks:
      - gii_project1_network
    volumes:
      - gii_project1_static:/home/GII_Project/staticfiles/
      - gii_project1_media:/home/GII_Project/media/

networks:
  gii_project1_network:

volumes:
  gii_project1_static:
  gii_project1_media: